name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          cargo install \
            mdbook@0.4.40 \
            mdbook-toc@0.14.2 \
            mdbook-alerts@0.6.8 \
            mdbook-codename@0.0.1

      - name: Build book
        run: mdbook build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'writing-hypervisor-in-zig'
          directory: 'book'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          wranglerVersion: '3'
